### ISSUE TITLE
💥 1.17 API breaks and stability

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#5153]
# 1.17 API Stability

With 1.17 hopefully being a just be around or a short time before 1.18 or whatever second half of the cliffs and caves update will be called, we will take this chance to make API breaks during the release cycle up to 1.18.

With this in mind, we might not follow semver fully to avoid ending up with version 123.4.5 or similar.
Addons or any other mod with a deeper integration will have to account for it and probably be either very strict about compatible releases or have to update frequently and fast.

# Planned API breaks for 1.17 *(TBD)*

## Storage Channels

* [x] Require a ResourceLocation when registering storage channels so they can be referenced in packets and obtained client-side (and vice-versa)
* [x] Allow storage channels to be looked up via the ID they have been registered with
* [x] Add getId() to IStorageChannel

## `IGrid` changes

* [x] [\<C extends IGridCache\> IGrid#getCache(Class<? extends IGridCache> iface)](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/api/java/appeng/api/networking/IGrid.java#L46)
Change to `<C extends IGridCache> C getCache(Class<C> iface);`
* [x] [MENetworkEvent IGrid#postEvent(MENetworkEvent ev);](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/api/java/appeng/api/networking/IGrid.java#L56)
Change to `<E extends MENetworkEvent> E IGrid#postEvent(E ev);`
* [x] [MENetworkEvent postEventTo(@Nonnull IGridNode node, @Nonnull MENetworkEvent ev);](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/api/java/appeng/api/networking/IGrid.java#L66)
Change to `<E extends MENetworkEvent> E postEventTo(IGridNode node,E ev);`
  - Method removed instead.

## `IGridCache` changes

* [x] `IGridCache#onUpdateTick()`. See #5150 for further details

## Part related changes. E.g. `IPartHost` or `IPart` 

* [x] Direct `replace()` instead of `remove(notRealRemove)` + `add()`. See #5128
* [x] Consider storing only the item id not the full itemstack for the cable bus/`IPartHost`. See #5170
* [x] Drop `appeng.api.parts.PartItemStack`. See #5171
* [x] Have `IPart#getDrops()` handle dropping the part itself. See #5169

## `INetworkEncodable` changes

* [x] Remove `name` parameter from `setEncryptionKey`
  - Done as `void unlink(ItemStack itemStack);` 
* [x] Consider removal, unless addons can actually do anything with the key
  - Keep, key is usable via `Locatables`. Renamed to `IGridLinkableHandler`. Shouldn't be implemented anymore, instead register as handler in `GridLinkables`.
* [x] `getEncryptionKey` make it return null (and add clarifying docs+annotation) rather than empty string
  - `IWirelessTerminalHandler` now has `OptionalLong getGridKey(ItemStack is);`
* [x] `setEncryptionKey` should also accept null for the key to clear it
  - `unlink` has been added

## `IUpgradeableHost` changes

* [x] Remove base interface `ISegmentedInventory`, make `getUpgradeInventory` non-default
* [x] Remove `getTile`
* [x] Rethink that it _requires_ `IConfigurableObject` to be extended
* [x] Connect  Upgrades.Supported with IUpgradeableHost  so that it becomes possible to check how many of an upgrade an upgradable host supports (i.e. by exposing getMaxSupported from the inventory)

## `IMovableTile` changes

* [x] Pass the new cluster dimensions to `IMovableTile#doneMoving()`. Or alternatively handle it via custom `IMovableHandler`?

## `ICellWorkbenchItem` changes

* [x] Change `getUpgradesInventory()` to only support 8 upgrades for easier rendering?

## `Removals`

* [x] Remove `AEPartLocation` (#5256)
* [x] Remove `IAEWrench ` (#5283)
* [x] Remove `IAEStack#asItemStackRepresentation()` (#5448)
